### ISSUE TITLE
how to remove history data

### ISSUE THREAD

**Issue by hongwei7458** [OpenSkywalking/skywalking-netcore#103]
hi friends , it's a great soft, 
now ,i have a problem :'no space left on device'
 when the history is to much ,how to remove ?

**Comment by liuhaoyang** [comment]
Can you provide more contextual information? Such as runtime environment, system version, and stack that throws exception.

**Comment by wu-sheng** [comment]
Are you talking about backend data or agent data?

**Comment by hongwei7458** [comment]
> Can you provide more context information? Such as runtime environment, system version, and stack that throws exception.
 dockerfile :docker run -p 9200:9200 -p 9300:9300 -e cluster.name=elasticsearch -e xpack.security.enabled=false --name=elasticsearch --restart=always -d wutang/elasticsearch-shanghai-zone
  skywalking :docker run -p 8080:8080 -p 10800:10800 -p 11800:11800 -p 12800:12800 -e ES_CLUSTER_NAME=elasticsearch -e ES_ADDRESSES= elasticsearchIP:9300 -d wutang/skywalking-docker:5.x

**Comment by liuhaoyang** [comment]
This is not agent issue, you can ask for help in the [SkyWalking](https://github.com/apache/incubator-skywalking/issues/new) repository
