### ISSUE TITLE
能否提供一个筛选，排除不需要统计的接口请求数据

### ISSUE THREAD

**Issue by landonzeng** [OpenSkywalking/skywalking-netcore#104]
能否提供一个筛选，排除不需要统计的接口请求数据，目前每次进去看数据都会有一堆健康监测的数据，想排除某个接口数据或者某几个接口数据
![qq 20181106181117](https://user-images.githubusercontent.com/7336781/48057677-95b68400-e1ef-11e8-9eca-aa083d57a48a.png)

**Comment by landonzeng** [comment]
还有是否能够统计一整个模块下的吞吐量等信息，也就是上图中的下拉列表里可以不选吗？只选择模块进行统计

**Comment by liuhaoyang** [comment]
Repeat with #79 .
