### ISSUE TITLE
Update Nuget Package

### ISSUE THREAD

**Issue by nadirakdag** [OpenSkywalking/skywalking-netcore#120]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Hello, When will you release next version and update nuget package, because of #99 issue we can't register necessary services to IServiceCollection in asp.net core. 
___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by liuhaoyang** [comment]
We are considering a new automated solution to make the agent easier to use, which can take weeks or more.

**Comment by nadirakdag** [comment]
This is a good news. Because easier to use means easier integrate. I would like to contribute, is there anything i can help or do ?
