### ISSUE TITLE
Could not load type 'SkyWalking.Diagnostics.ITracingDiagnosticProcessor' from assembly 'SkyWalking.Abstractions, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null' 

### ISSUE THREAD

**Issue by CrazyJson** [OpenSkywalking/skywalking-netcore#122]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [√ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
windows,asp.net core2.0
![image](https://user-images.githubusercontent.com/8163485/50505082-96132300-0aac-11e9-90b0-0d54c7cdd33f.png)

- Which company or project?

- What happen?
项目启动报以下异常
Could not load type 'SkyWalking.Diagnostics.ITracingDiagnosticProcessor' from assembly 'SkyWalking.Abstractions, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null' 

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by liuhaoyang** [comment]
Can you provide a demo to reproduce this problem?

**Comment by CrazyJson** [comment]
- 
[WebApplication1.zip](https://github.com/OpenSkywalking/skywalking-netcore/files/2716421/WebApplication1.zip)

**Comment by CrazyJson** [comment]
Demo project has been uploaded

**Comment by liuhaoyang** [comment]
Incompatible between 0.6 and 0.3 versions.
```
    <PackageReference Include="SkyWalking.AspNetCore" Version="0.3.0" />
    <PackageReference Include="SkyWalking.Diagnostics.EntityFrameworkCore.Pomelo.MySql" Version="0.6.0" />
```
