### ISSUE TITLE
Fluent API configure support

### ISSUE THREAD

**Issue by 1015450578** [OpenSkywalking/skywalking-netcore#127]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement

It seems 'SkyWalking.Agent.AspNetCore' is more difficult to use than SkyWalking.AspNetCore.
This limits me to configure it in more ways, such as UserSecrets.
I like the way out-of-the-box in before version 'SkyWalking.AspNetCore'

**Comment by 1015450578** [comment]
services.AddSkyWalking(options=>{
  options.ApplicationCode="code";
  options.Servers="servers"
}).AddSqlClient().AddEFCore().AddHttp().AddAspNetCore().AddOther()

Just like Microsoft.Extensions.Authentication

services.AddAuthentication().AddCookies()

I can choose any custom data I want to track.

**Comment by liuhaoyang** [comment]
We have done so many attempts in the direction of the automatic probes to minimize the intrusion of application code, and the more friendly integration with devops. I don't recommend exposing too many manual apis.
