### ISSUE TITLE
Add client info collecting

### ISSUE THREAD

**Issue by carterHe** [OpenSkywalking/skywalking-netcore#40]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x ] Requirement

___
### Requirement or improvement
There is a situation  that we have many nodes would submit the data to central service, there were be slowly or fast, we did't found the slowly request where does it from? Why does it be slowly?

If we can collect the original datas from request, the client ip, that it will be a easy way to  improve our system.

Otherwise,  we are also like to collect the stacktrace when a exception thrown.

Sincerely hope that features will be provided.

Best wish to Skywalking Team!

Thanks!

**Comment by wu-sheng** [comment]
Thanks for your feedback. It is exciting to have this, considering .net agent project is so young.

Let me clear about your proposals.
1. What do you mean about original data? http request parameter? If so, have you considered that, this is a high payload features. Do you system have resources, e.g. CPU, memory, network, for this.
2. Exception stack should be collected by agent, if there is no catch to just log the exception.This needs @liuhaoyang 's confirm.
3. Apache SkyWalking backend show every service and server( node) performance, which may could help you find out the pattern, whether some service or server have a long latency.

**Comment by liuhaoyang** [comment]
Collect the exception messages and http request logs are already in the plan.

**Comment by carterHe** [comment]
@wu-sheng 

Thanks for your reply.

> What do you mean about original data? http request parameter? If so, have you considered that, this is a high payload features. Do you system have resources, e.g. CPU, memory, network, for this.

Yes, hope to consider set a configuration to turn on/off the request parameter. 

Also, My I know got the `Content-Length` or Request headers has more effect for service  performance?

>Exception stack should be collected by agent, if there is no catch to just log the exception.This needs @liuhaoyang 's confirm.

As @liuhaoyang  remind before, we will trace the exception at next version.

>Apache SkyWalking backend show every service and server( node) performance, which may could help you find out the pattern, whether some service or server have a long latency.

It's more convenient to help us improve service performance. Thanks for your contributions.

Regards.

**Comment by liuhaoyang** [comment]
I have already supported record http request logs and exception stacks in https://github.com/OpenSkywalking/skywalking-netcore/pull/42.

**Comment by wu-sheng** [comment]
> Yes, hope to consider set a configuration to turn on/off the request parameter.

@carterHe Someone used to ask for this in SkyWalking-java. I am open to those settings, but I have to say, implement these requires a lot of time. So this depends on the community.
