### ISSUE TITLE
when using skywalking in docker ,state of the gRpc Channel is always Idle

### ISSUE THREAD

**Issue by zpf1989** [OpenSkywalking/skywalking-netcore#58]
I'm using skywalking in docker,and exposed the ports:10800、11800、12800.
![image](https://user-images.githubusercontent.com/16696623/41349067-46351354-6f41-11e8-8e7d-f878a73b1227.png)

When I start the sample project of skywalking-netcore,it fails at the first connection,and the follows connections are ok,as below:
![image](https://user-images.githubusercontent.com/16696623/41348878-9f9a246c-6f40-11e8-81c0-dc959f6a1e8c.png)
But it can not work to send trace data to Skywalking.
I debugged the code ,and find that the state of the Channel is alwayes Idle,and Application can not registerd.
![channle-idle](https://user-images.githubusercontent.com/16696623/41348972-f27dfe88-6f40-11e8-8c3c-13cd585a01ac.png)
It may be something wrong with my environment,but I really can't solve the problem.
So,could you master give a help?
Thanks a lot!

**Comment by zpf1989** [comment]
I'm using aspnetcore app in host(windows 10+hyper-v),and the docker is also in the host,
Below is my app setting:
![image](https://user-images.githubusercontent.com/16696623/41349165-994118fe-6f41-11e8-8ac8-5684ac1cce9c.png)

**Comment by wu-sheng** [comment]
@liuhaoyang Is the .net agent using the direct link? Or service discovery by naming?

**Comment by liuhaoyang** [comment]
@zpf1989 I did not reproduce your problem. 
- OS : Mac OSX 10.13.4 
- docker image : centos latest
- SkyWalking Collector : 5.0.0 beta
- SkyWalking .Net Core : 0.3.0-preview
- dotnet runtime: 2.1.301

**Comment by liuhaoyang** [comment]
@wu-sheng  Currently .NET agent only support direct link . 
@zpf1989 I'm not sure if this issue will only occur in windows container, once you occur the same problem again, please reopen this issue.
