### ISSUE TITLE
是否能改善计录时间戳的精度

### ISSUE THREAD

**Issue by wang9563** [OpenSkywalking/skywalking-netcore#64]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Improvement
- 是否可以用 `Stopwatch.GetTimestamp()  - 62135596800000L`  来代替 `DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()` 来记录时间戳？这样时间精度高，耗时记录的也更准确些。
http://jaychapman.blogspot.com/2007/12/datetimenow-precision-issues-enter.html
https://stackoverflow.com/questions/28637/is-datetime-now-the-best-way-to-measure-a-functions-performance

**Comment by liuhaoyang** [comment]
`Stopwatch.GetTimestamp() - 62135596800000L` cannot get unix timestamp. See  [how-to-get-a-unix-timestamp-from-stopwatch-gettimestamp](https://stackoverflow.com/questions/37839578/how-to-get-a-unix-timestamp-from-stopwatch-gettimestamp)
