### ISSUE TITLE
No Active Span异常

### ISSUE THREAD

**Issue by 846677234** [OpenSkywalking/skywalking-netcore#73]
当循环并行调用HttpClient请求时，会偶发性得报如下异常
![image](https://user-images.githubusercontent.com/6667502/42920200-1909c546-8b48-11e8-971a-bd642bb8ded7.png)
我的场景是，使用MediatR循环发布一个事件，有两个订阅，两个订阅内部都是HttpClient请求

**Comment by liuhaoyang** [comment]
Could you provide some demo for us?

**Comment by 846677234** [comment]
@liuhaoyang 
使用的是MediatR，一个中介者库
先定义一个事件
![image](https://user-images.githubusercontent.com/6667502/42920553-e3474ea4-8b49-11e8-9785-b05a3c0657f8.png)
然后两个订阅者，内部都是一个http请求
![image](https://user-images.githubusercontent.com/6667502/42920583-1074d23e-8b4a-11e8-86c0-fcf3c17fde4c.png)
![image](https://user-images.githubusercontent.com/6667502/42920588-14adbce4-8b4a-11e8-840f-fd7e7d29fbf4.png)
然后接口中循环发布这个事件
![image](https://user-images.githubusercontent.com/6667502/42920632-47b7663a-8b4a-11e8-9412-7d6e70eb4449.png)
很快就会出现上面那个异常，100%重现

**Comment by 846677234** [comment]
#67 之前没有看到这个bug fix，看来已经解决了
