### ISSUE TITLE
关于cap的疑问

### ISSUE THREAD

**Issue by kingreatwill** [OpenSkywalking/skywalking-netcore#74]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
-有个疑问
![image](https://user-images.githubusercontent.com/13087689/43001976-c722ba18-8c59-11e8-88c9-ca4c9168d258.png)
![image](https://user-images.githubusercontent.com/13087689/43002016-e7756234-8c59-11e8-99d8-a73de6aa0dd9.png)
这些不应该在一个TraceId里面吗？不然我怎么追踪一系列的操作？

**Comment by yuleyule66** [comment]
Please show your configuration

**Comment by kingreatwill** [comment]
![image](https://user-images.githubusercontent.com/13087689/43052488-c8019aa2-8e58-11e8-94e1-5ceeffafad57.png)
[sample.zip](https://github.com/OpenSkywalking/skywalking-netcore/files/2217614/sample.zip)

**Comment by kingreatwill** [comment]
@yuleyule66 有时间看下我这个问题么？
