### ISSUE TITLE
skywalking-netcore 跟踪pgsql问题

### ISSUE THREAD

**Issue by littlehuihui** [OpenSkywalking/skywalking-netcore#78]
Question
- 在使用skywalking-netcore做SQL Trace相关验证，用于跟踪SqlServer时是可以实现正常跟踪的；在用于跟踪pgsql时，从dashboard页面可以看到有DB数据源，但是trace页面看不到具体的SQL信息，请问sw对不同数据库访问组件使用方式有什么不同吗？
谢谢！

![image](https://user-images.githubusercontent.com/11981613/44712381-32b7bb00-aae3-11e8-8032-64a5143b8784.png)

![image](https://user-images.githubusercontent.com/11981613/44712472-685ca400-aae3-11e8-9556-da640dacbbbb.png)

**Comment by yuleyule66** [comment]
Thanks for your report , let me answer your question.

Because of the database driver for PostgreSql does not yet support the Diagnostics feature, so we currently  have not implemented tracking support for the PostgreSql.

**Comment by wu-sheng** [comment]
I think even SkyWalking Java agent doesn't support PostgreSQL right now. :)

**Comment by littlehuihui** [comment]
问题已解决，感谢各位老师热心解答~

**Comment by Aric000** [comment]
2015年，这个问题解决了吗
