### ISSUE TITLE
how to use it on docker ?

### ISSUE THREAD

**Issue by liguobao** [OpenSkywalking/skywalking-netcore#95]
- [* ] Question or discussion

### Question

On Windows/Mac/Linux,we can use it by
```
dotnet tool install -g SkyWalking.DotNet.CLI
```
but  docker dotnet-runtime not contains dotnet SDK.

that will get this error.
```
Step 11/12 : RUN dotnet tool install -g SkyWalking.DotNet.CLI
 ---> Running in b5e22d93ce49
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
The command '/bin/sh -c dotnet tool install -g SkyWalking.DotNet.CLI' returned a non-zero code: 145
```

What should I do?

### Requirement or improvement
- microsoft/dotnet:2.1.3-aspnetcore-runtime

**Comment by MeetOct** [comment]
same question  to me, dotnet tool command is only installed with .net core sdk.

**Comment by liuhaoyang** [comment]
Thank you @witskeeper . Using a two-stage build is a good solution.
