### ISSUE TITLE
Requirement for supporting mysql

### ISSUE THREAD

**Issue by beckjin** [OpenSkywalking/skywalking-netcore#97]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

**Comment by liuhaoyang** [comment]
Already supported https://github.com/OpenSkywalking/skywalking-netcore/tree/master/src/SkyWalking.Diagnostics.MySqlData
