### ISSUE TITLE
Please consider setting ServiceCollectionExtensions to public

### ISSUE THREAD

**Issue by beckjin** [OpenSkywalking/skywalking-netcore#99]
If it's public, we can install SkyWalking. Agent. AspNetCore via the nuget package,  use services.AddSkyWalkingCore () in ConfigureServices.

![default](https://user-images.githubusercontent.com/7261408/47611958-377cf900-daab-11e8-8937-83f5f4febf03.PNG)

```
public void ConfigureServices(IServiceCollection services)
{
	services.AddSkyWalkingCore();
	services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
}
```

**Comment by beckjin** [comment]
OK

**Comment by liuhaoyang** [comment]
Install `SkyWalking.Agent.AspNetCore` package, then add the assembly name of `SkyWalking.Agent.AspNetCore` to the `ASPNETCORE_HOSTINGSTARTUPASSEMBLIES` environment variable.

**Comment by beckjin** [comment]
Of course, this is a way.
